// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PollCase.Data.Contexts;

namespace PollCase.Data.Migrations
{
    [DbContext(typeof(PollCaseDbContext))]
    [Migration("20200316150055_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PollCase.Data.Models.Options", b =>
                {
                    b.Property<int>("option_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("option_description");

                    b.Property<int>("option_votes");

                    b.Property<int>("poll_id");

                    b.HasKey("option_id");

                    b.HasIndex("poll_id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("PollCase.Data.Models.Poll", b =>
                {
                    b.Property<int>("poll_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("poll_description");

                    b.Property<int>("poll_views");

                    b.HasKey("poll_id");

                    b.ToTable("Poll");
                });

            modelBuilder.Entity("PollCase.Data.Models.Options", b =>
                {
                    b.HasOne("PollCase.Data.Models.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("poll_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
